# Columns to drop during data cleaning
drop_cols:
  - "pos_touches"
  - "Att Pen"
  - "id"

# Categorical columns used in the analysis
categorical_columns:
  - "id"
  - "element_type"
  - "web_name"
  - "team_name"
  - "opponent_team_name"
  - "was_home"
  - "gameweek"

numerical_columns:
  - "element_type"
  - "gameweek"
  - "minutes"
  - "GC"
  - "CS"
  - "now_cost"
  - "selected_by_percent"
  - "shots"
  - "SoT"
  - "SiB"
  - "xG"
  - "npxG"
  - "G"
  - "npG"
  - "key_passes"
  - "xA"
  - "A"
  - "xGC"
  - "xCS"
  - "xGI"
  - "npxGI"
  - "xP"
  - "PvsxP"
  - "carries_final_third"
  - "carries_penalty_area"
  - "clearances"
  - "shot_blocks"
  - "interceptions"
  - "recoveries"
  - "tackles"
  - "touches"
  - "penalty_area_touches"
  - "Att Pen"
  - "pos_touches"
  - "clearances_blocks_interceptions"
  - "defensive_contribution"

# Target column for model training
target_column:
  - "total_points"

# API Configuration (Ensure the API key is handled securely)
api_config:
  url: "https://api.football-data.org/v4/competitions/PL/matches"
  api_key: "your_api_key_here"  # Replace with a secure method to handle the API key

# Mapping of team names from the API to standardized names
team_name_mapping:
  Arsenal FC: "Arsenal"
  Fulham FC: "Fulham"
  Aston Villa FC: "Aston Villa"
  Southampton FC: "Southampton"
  AFC Bournemouth: "Bournemouth"
  Tottenham Hotspur FC: "Tottenham"
  Brentford FC: "Brentford"
  Brighton & Hove Albion FC: "Brighton"
  Leicester City FC: "Leicester"
  Chelsea FC: "Chelsea"
  Crystal Palace FC: "Crystal Palace"
  Everton FC: "Everton"
  Ipswich Town FC: "Ipswich"
  Liverpool FC: "Liverpool"
  Manchester City FC: "Manchester City"
  Manchester United FC: "Manchester United"
  West Ham United FC: "West Ham"
  Newcastle United FC: "Newcastle United"
  Nottingham Forest FC: "Nottingham Forest"
  Wolverhampton Wanderers FC: "Wolverhampton Wanderers"
  Burnley FC: "Burnley"
  Leeds United FC: "Leeds United"
  Sheffield United FC: "Sheffield United"
  Sunderland AFC: "Sunderland"
  Watford FC: "Watford"

# scout gw prediction
gw_team_name_mapping:
  'Arsenal': 'Arsenal'
  'Aston Villa': 'Aston Villa'
  'Bournemouth': 'Bournemouth'
  'Brentford': 'Brentford'
  'Brighton': 'Brighton'
  'Chelsea': 'Chelsea'
  'Crystal Palace': 'Crystal Palace'
  'Everton': 'Everton'
  'Fulham': 'Fulham'
  'Ipswich': 'Ipswich'
  'Leicester': 'Leicester'
  'Liverpool': 'Liverpool'
  'Man City': 'Manchester City'
  'Man Utd': 'Manchester United'
  'Newcastle': 'Newcastle United'
  "Nott'm Forest": 'Nottingham Forest'
  'Southampton': 'Southampton'
  'Spurs': 'Tottenham'
  'West Ham': 'West Ham'
  'Wolves': 'Wolverhampton Wanderers'
  'Leeds': 'Leeds United'


# Model Information
models:
  linear_regression:
    version: "v4.0"
    last_trained: "February 8, 2026"
    path: "models/linear_regression_reg.pkl"
    year: 2025-2026

  xgboost:
    version: "v4.0"
    last_trained: "February 8, 2026"
    path: "models/xgboost_reg.pkl"
    year: 2025-2026

  catboost:
    version: "v3.0"
    last_trained: "February 8, 2026"
    path: "models/catboost_reg.pkl"
    year: 2025-2026


version: "4.5.0"
